export const dadosFake = [
  {
    "id": "1",
    "fotoCapa": "https://assets.volkswagen.com/is/image/volkswagenag/1920x1080_5?Zml0PWNyb3AsMSZmbXQ9d2VicCZxbHQ9Nzkmd2lkPTE5MjAmaGVpPTEwODAmYWxpZ249MC4wMCwwLjAwJmJmYz1vZmYmM2E1Nw==",
    "titulo": "Novo modelo de jetta",
    "descricao": "O novo Jetta apresenta um design elegante e moderno, combinando linhas aerodinâmicas com acabamentos sofisticados que destacam sua presença nas ruas. Sob o capô, oferece opções de motorização potentes e eficientes, incluindo versões híbridas para quem busca desempenho aliado à sustentabilidade.",
    "noticia":
      "O novo Jetta apresenta um design elegante e moderno, combinando linhas aerodinâmicas com acabamentos sofisticados que destacam sua presença nas ruas. Sob o capô, oferece opções de motorização potentes e eficientes, incluindo versões híbridas para quem busca desempenho aliado à sustentabilidade. Por dentro, o sedan impressiona com tecnologia de ponta, como um painel digital personalizável, conectividade avançada com smartphones e um sistema de som premium. Além disso, o Jetta prioriza a segurança com recursos como assistência de frenagem, detecção de ponto cego e piloto automático adaptativo. Com conforto de sobra e um amplo porta-malas, ele é a escolha ideal para quem valoriza estilo, desempenho e funcionalidade.",
  },
  {
    "id": "2",
    "fotoCapa": "https://www.chevrolet.com.br/content/dam/chevrolet/south-america/brazil/portuguese/index/portable-navigation/jellys/site-jpg-404-161.jpg?imwidth=1920",
    "titulo": "S10 atola no riacho",
    "descricao": "Uma S10 indo a 400km por hora, atola em um riacho em carapicuipa, com o motorista comendo um sanduiche e o passageiro comendo um bolo de chocolate.",
    "noticia":
    "Carapicuíba, uma cidade normalmente conhecida por seu ritmo tranquilo e ruas bem asfaltadas, se viu abalada por um evento inusitado. Naquela tarde ensolarada, um veículo S10, impulsionado por um motor aparentemente alucinógeno, rompeu a barreira dos 400 km/h, transformando a pacata via em uma pista de corrida improvável. \n Ao volante, um sujeito completamente alheio à velocidade vertiginosa que atingia, concentrava-se em saborear um sanduíche caprichado. Ao seu lado, um passageiro igualmente despreocupado com a situação, deliciava-se com um bolo de chocolate. A combinação da velocidade insana com a tranquilidade dos ocupantes era surreal. A aventura, no entanto, estava longe de terminar. Em meio à velocidade desenfreada, a S10 encontrou um obstáculo inesperado: um pequeno riacho que cortava a estrada. A água, antes tranquila, foi violentamente cortada pela picape, que, impulsionada pela inércia, mergulhou de frente. O impacto foi brutal. A S10, agora transformada em um submarino terrestre, afundou no riacho, levando consigo os dois ocupantes ainda atônitos com a reviravolta dos acontecimentos. O sanduíche e o bolo de chocolate, antes símbolos de um passeio tranquilo, agora jaziam submersos, testemunhas mudas de uma jornada épica. A notícia se espalhou rapidamente, transformando a pequena Carapicuíba em uma cidade das atenções. A polícia, os bombeiros e uma multidão curiosa cercaram o local do acidente, tentando decifrar o mistério por trás daquela velocidade absurda e do desfecho inesperado. A S10 foi retirada do riacho, mas a pergunta que ficou no ar era: como uma picape comum pôde atingir tal velocidade? E mais importante, como os ocupantes conseguiram sair ilesos de tamanha aventura? As teorias mais absurdas ganharam força, desde a existência de um motor experimental até a interferência de forças extraterrestres. A história da S10 voadora, como ficou conhecida, se tornou uma lenda local, um lembrete de que até mesmo em uma cidade tranquila, o inesperado pode acontecer. E quem diria que um sanduíche e um bolo de chocolate poderiam ser os protagonistas de uma história tão épica?",
  }
]
